### ISSUE TITLE
ConstrutctorBoyd crash

### ISSUE THREAD

**Issue by jarlrasm** [jarlrasm/PhilTheCartographer#13]
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.MemberAccessExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.
   at Phil.Refactorings.FillConstrutorBodyRefactoring.FixConstructorBody.<>c__DisplayClass11_1.<GetUnimplemntedProperties>b__3(AssignmentExpressionSyntax y)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source,Func`2 predicate)
   at Phil.Refactorings.FillConstrutorBodyRefactoring.FixConstructorBody.<>c__DisplayClass11_0.<GetUnimplemntedProperties>b__0(IPropertySymbol x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at Phil.Extensions.SymbolExtensions.IsMissing(IPropertySymbol symbol,IEnumerable`1 mssingParameters)
   at Phil.Refactorings.FillConstrutorBodyRefactoring.FixConstructorBody.<>c__DisplayClass9_0.<ImplementConstructorBody>b__1(IPropertySymbol x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Phil.Refactorings.FillConstrutorBodyRefactoring.FixConstructorBody.ImplementConstructorBody(BlockSyntax declaration,String sourcename,ITypeSymbol targetTypeInfo,ITypeSymbol sourceType)
   at async Phil.Refactorings.FillConstrutorBodyRefactoring.FixConstructorBody.GetChangedDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavor(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavors(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by jarlrasm** [comment]
System.NullReferenceException : Object reference not set to an instance of an object.
   at Phil.Refactorings.FillConstrutorBodyRefactoring.ImplementsSomethingFor(TypeSyntax type,IEnumerable`1 unimplemntedProperties,SemanticModel semanticModel)
   at Phil.Refactorings.FillConstrutorBodyRefactoring.<>c__DisplayClass2_0.<ReportForUnimplemented>b__0(ParameterSyntax x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at Phil.Refactorings.FillConstrutorBodyRefactoring.ReportForUnimplemented(CodeRefactoringContext context,IEnumerable`1 unimplemntedProperties,SemanticModel semanticModel,ConstructorDeclarationSyntax node)
   at async Phil.Refactorings.FillConstrutorBodyRefactoring.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
